export const AI_ACADEMIC_ANALYSIS_PURPOSE = "AI_ACADEMIC_ANALYSIS";
export const AI_CONSENT_VERSION = "2026-08-30-v1";
export const GROQ_STUDY_CHAT_PURPOSE = "GROQ_STUDY_CHAT";
export const GROQ_STUDY_CHAT_CONSENT_VERSION = "2026-10-02-v1";
export const ACCOUNT_DELETION_CONFIRMATION = "EXCLUIR MINHA CONTA";
